---
- name: Configure shorty infrastructure
  hosts: all
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yml
  roles:
    - configure-server
    - configure-prometheus-node-exporter

