---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: yes
    apt:
      autoremove: yes

  - name: "install make"
    become: yes
    apt:
      name: ["make"]
      update_cache: yes

  - name: "install make"
    become: yes
    make: 
      target: "install-all"

  - name: "Start Minikube"
    become: yes
    make: 
      target: "start_minikube"

  - name: "Run Kubes"
    become: yes
    make:
      target: "run_kubes"