---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: yes
    apt:
      autoremove: yes

  - name: "Copy Makefile"
    become: true
    copy:
      src: Makefile
      dest: .

  - name: "install make"
    become: yes
    apt:
      name: ["make"]
      update_cache: yes

  - name: "start_minikube"
    shell: minikube start

  - name: "Copy deployment.yml"
    become: true
    copy:
      src: deployment.yml
      dest: .

  - name: "Deploy Kubes"
    make:
      chdir: .
      target: "deploy"

  - name: "run shorty service"
    become: true
    shell: minikube service shorty-service