---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: yes
    apt:
      autoremove: yes

  - name: "add node exporter configuration."
    become: true
    copy:
      src: Makefile
      dest: .

  - name: "install make"
    become: yes
    apt:
      name: ["make"]
      update_cache: yes

  - name: "install docker"
    become: yes
    make:
      chdir: .
      target: "install-docker"

  - name: "install hadolint"
    become: yes
    make:
      chdir: .
      target: "install-hadolint"

  - name: "install minikube"
    become: yes
    make:
      chdir: .
      target: "install-minikube"

  - name: "Start Minikube"
    become: yes
    make: 
      chdir: .
      target: "start_minikube"

  - name: "Run Kubes"
    become: yes
    make:
      chdir: .
      target: "run_kubes"