---
  - name: "update apt packages."
    become: yes
    apt-get:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt-get:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: yes
    apt-get:
      autoremove: yes

  - name: "add node exporter configuration."
    become: true
    copy:
      src: Makefile
      dest: .

  - name: "install make"
    become: yes
    apt-get:
      name: ["make"]
      update_cache: yes

  - name: "install make"
    become: yes
    make:
      chdir: .
      target: "install-all"

  - name: "Start Minikube"
    become: yes
    make: 
      chdir: .
      target: "start_minikube"

  - name: "Run Kubes"
    become: yes
    make:
      chdir: .
      target: "run_kubes"