version: "3"
services:
  app:
    container_name: flask
    restart: unless-stopped
    build: .
    ports:
      - "80:5000"
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=secret
      - MONGO_URI=YOUR_MONGO_URI
      - MONGO_TEST_URI=YOUR_MONGO_TEST_URI
      - DOMAIN=YOUR_DOMAIN
      - ACCESS_TOKEN=YOUR_ACCESS_TOKEN
