version: 2.1
defaultDockerImage: &defaultDockerImage
  docker:
    - image: circleci/python:3.7.0-browsers
      environment:
        SECRET_KEY: ${SECRET_KEY}
        MONGO_URI: ${MONGO_URI}
        MONGO_TEST_URI: ${MONGO_TEST_URI}
        DOMAIN: ${DOMAIN}
        ACCESS_TOKEN: ${ACCESS_TOKEN}

jobs:
  build:
    <<: *defaultDockerImage
    steps:
      - checkout
      - restore_cache:
          keys:
              - v-pip-deps-{{ checksum "requirements.txt" }}
              - v-pip-deps-
      - run: make setup
      - run: source ~/venv/bin.activate
      - run: make install
      - save_cache:
          key: v-pip-deps-{{ checksum "requirements.txt" }}
          paths:
            - ~/venv

  test:
    <<: *defaultDockerImage
    steps:
      - checkout
      - run: source ~/venv/bin.activate
      - restore_cache:
          keys:
              - v-pip-deps-{{ checksum "requirements.txt" }}
              - v-pip-deps-
      - run: python3 manage.py test

workflows:
  automate_flask_app:
    jobs:
      - build
      - test:
          requires:
            - build
