apiVersion: v1
kind: Ingress
metadata:
  name: shorty-ingress
spec:
  defaultBackend:
    service:
      name: shorty
      port:
        number: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorty
spec:
  selector:
    matchLabels:
      app: shorty
  template:
    metadata:
      labels:
        app: shorty
    spec:
      containers:
      - name: shorty
        image: urokai/udacity-cloud-devops-capestone
        ports:
        - containerPort: 5000