apiVersion: v1
kind: Service
metadata:
  name: shorty-service
spec:
  selector:
    app: shorty
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shorty
spec:
  selector:
    matchLabels:
      app: shorty
  replicas: 2
  template:
    metadata:
      labels:
        app: shorty
    spec:
      containers:
      - name: shorty
        image: urokai/udacity-cloud-devops-capestone
        imagePullPolicy: Never
        ports:
        - containerPort: 5000